export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_BACKLOG_ITEMS = 'GET_BACKLOG_ITEMS';
export const BACKLOG_LOADING = 'BACKLOG_LOADING';
export const CLEAR_BACKLOG = 'CLEAR_BACKLOG';
export const REMOVE_TASK = 'REMOVE_TASK';
